version: '3.5'

services:
  postgres-account:
    image: postgres
    container_name: postgres-acmepay
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=acme_pay_db
    volumes:
      - "./data/accounts/postgres:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - 5433:5432